// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgdnjgmvvofnkdkpykuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnZG5qZ212dm9mbmtka3B5a3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NzU4MTEsImV4cCI6MjA3NDA1MTgxMX0.Ft79kp9KreCiQ9GXbKl9SudqwDQLzgVGYkAkE8nLk3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});